project:
  type: website
  output-dir: docs

website:
  title: "History of Cartography"
  sidebar: 
    contents: 
#      - section: "Overview"
#        contents: 
      - index.qmd
#          - syllabus.qmd
      - text: "---"    
      - section: "The Ancient World"
        contents: 
          - first.qmd
      - section: "The Classical World"
        contents:   
          - eratosthenes.qmd
          - ptolemaios.qmd
      - section: "The Medieval World"
        contents: 
          - hereford.qmd
          - framauro.qmd
          - idrisi.qmd
          - kangnido.qmd
      - section: "The Age of Discovery"
        contents: 
          - waldseemuller.qmd
          - mercator.qmd
      - section: "The Age of Empire"
        contents: 
          - colomb.qmd
      - section: "The Modern World"
        contents: 
          - peters.qmd
      - text: "---"    
      - section: "Epilogue"    

  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024, Sang-Il Lee"
    right: 
      - icon: house
        href: https://sangillee.snu.ac.kr/
      - icon: envelope
        href: mailto:si_lee@snu.ac.kr
      - icon: github
        href: https://github.com/sangillee66
    border: true
  repo-url: https://github.com/sangillee66/class_2024_1_history_cartography
  repo-actions: [issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual

