project:
  type: website
  output-dir: docs

website:
  title: "2024/1 History of Cartography"
  sidebar: 
    contents: 
      - section: "Class Overview"
        contents: 
          - index.qmd
          - syllabus.qmd
      - text: "---"    
      - section: "10 Maps"
        contents: 
          - outline.qmd
          - eratosthenes.qmd
          - ptolemaios.qmd
          - hereford.qmd
          - framauro.qmd
          - idrisi.qmd
          - kangnido.qmd
          - waldseemuller.qmd
          - mercator.qmd
          - colomb.qmd
          - peters.qmd
      - text: "---"    
      - section: "Epilogue"    

  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024, Sang-Il Lee"
    right: 
      - icon: house
        href: https://sangillee.snu.ac.kr/
      - icon: envelope
        href: mailto:si_lee@snu.ac.kr
      - icon: github
        href: https://github.com/sangillee66
    border: true
  repo-url: https://github.com/sangillee66/class_2024_1_history_cartography
  repo-actions: [issue]

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual

