---
title: "Eratosthenes"
date-modified: last-modified
number-sections: false
bibliography: references.bib
---

## Synopsis

## References

-   Agbebaku, Henry Usiobaifo. 2019. “[Comparative Analysis of the Contributions of Strabo and Eratosthenes to the Development of Geography](papers/agbebaku_2019.pdf).” *Zaria Geographer* 26 (1): 70–82.

-   **Berg, Thomas Reinertsen**. 2018. *Theater of the World: The Maps That Made History*. New York: Little, Brown; Company. Like Frogs about a Pond. 29-61.

-   **Bianchetti, Serena.** 2016. “[The “Invention” of Geography: Eratosthenes of Cyrene.](papers/bianchetti_2016.pdf)” In *Brill's Companion to Ancient Geography*, edited by Hans-Joachim Gehrke, Michele Cataudella, and Serena Bianchetti, 132–49. Leiden, The Netherlands: BRILL. <https://doi.org/10.1163/9789004284715_009>.

-   Bunbury, E. H. 1959. *A History of Ancient Geography Among the Greeks and Romans from the Earliest Ages till the Fall of the Roman Empire*. Vol. 1. New York: Dover Publications.

-   Bunbury, E. H. 1959. *A History of Ancient Geography Among the Greeks and Romans from the Earliest Ages till the Fall of the Roman Empire*. Vol. 2. New York: Dover Publications.

-   Connors, Catherine. 2011. “[Eratosthenes, Strabo, and the Geographer’s Gaze](papers/connors_2011.pdf).” *Pacific Coast Philology* 46 (2): 139–52. <https://doi.org/10.2307/41851022>.

-   Dilke, Oswald Ashton Wentworth. 1985. *Greek and Roman Maps*. Ithaca, N.Y: Cornell University Press. II Evidence from Ancient Greece. 21-38.

-   **Irby, Georgia L.** 2012. “[Mapping the World: Greek Initiatives from Homer to Eratosthenes](papers/irby_2012.pdf).” *Ancient Perspectives: Maps and Their Place in Mesopotamia, Egypt, Greece, and Rome* 16: 81–107. 

-   Marx, Christian. 2015. “[An Analysis of the Latitudinal Data of Eratosthenes and Hipparchus](papers/mark_2015.pdf).” *Mathematics and Mechanics of Complex Systems* 3 (4): 309–39. <https://doi.org/10.2140/memocs.2015.3.309>.

-   McPhail, Cameron. 2011. “[Reconstructing Eratosthenes’ Map of the World: A Study in Source Analysis](papers/mcphail_2011).” PhD thesis, Dunedin, New Zealand.

-   **MyOldMaps**, [#112 Eratosthenes](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/112-eratosthenes/). (also see [#105](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/105-homer/), [#106](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/105-homer/106-ancient-greek-world/), [#107](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/105-homer/106-ancient-greek-world/107-anaximander/), [#108](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/108-hecataeus/), [#109](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/109-herodotus/), [#111](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/111-dicaearchus-of-messana/))

-   Oh, Jun-Young. 2017. “[Understanding the Estimation of Circumference of the Earth by of Eratosthenes Based on the History of Science, For Earth Science Education](papers/oh_2017.pdf).” *Journal of the Korean Society of Earth Science Education* 10 (2): 214–25. <https://doi.org/10.15523/JKSESE.2017.10.2.214>.

-   **Roller, Duane W.** 2012. ed. *Eratosthenes’ Geography*. Princeton, N.J: Princeton University Press.

-   **Roller, Duane W.** 2015. *Ancient Geography: The Discovery of the World in Classical Greece and Rome*. Bloomsbury Publishing. Chapter 6: Eratosthenes and The Invention of the Discipline of Geography, 121-135.

-   Russo, Lucio. 2013. “[Ptolemy’s Longitudes and Eratosthenes’ Measurement of the Earth’s Circumference](papers/russo_2013.pdf).” *Mathematics and Mechanics of Complex Systems* 1 (1): 67–79. <https://doi.org/10.2140/memocs.2013.1.67>.

-   Shcheglov, Dmitry A. 2004. “[Ptolemy’s System of Seven Climata and Eratosthenes’ Geography.](papers/shcheglov_2004.pdf)” *Geographia Antiqua* 13: 21–37.

-   Shcheglov, Dmitry A. 2006. “[Eratosthenes’ Parallel of Rhodes and the History of the System of Climata](papers/shcheglov_2006.pdf).” *Klio* 88 (2): 351–59. <https://doi.org/10.1524/klio.2006.88.2.351>.

-   **Shcheglov, Dmitry A**. 2016. “[The Error in Longitude in Ptolemy’s *Geography* Revisited](papers/shcheglov_2016.pdf).” *The Cartographic Journal* 53 (1): 3–14. <https://doi.org/10.1179/1743277414Y.0000000098>.

-   **Shcheglov, Dmitry A.** 2017. “[Eratosthenes’ Contribution to Ptolemy’s Map of the World](papers/shcheglov_2017.pdf).” *Imago Mundi* 69 (2): 159–75. <https://doi.org/10.1080/03085694.2017.1312112>.

-   Thomson, James Oliver. 1965. *History of Ancient Geography*. Biblo & Tannen Publishers.

-   김명남 옮김. 2015. [지도 위의 인문학](https://www.yes24.com/Product/Goods/23544580): 지도 위에 그려진 인류 문명의 유쾌한 탐험, 파주: 다산북스. (Garfield, Simon. 2013. [*On the Map: A Mind-expanding Exploration of the Way the World Looks*](https://www.amazon.com/Map-Mind-Expanding-Exploration-Notable-Adults/dp/1592407803/ref=sr_1_1?crid=3BJW1GMAX4YZ5&dib=eyJ2IjoiMSJ9.lQGK5iKst9YJ8yMba6Ck0TRUHjQNFMzmbWXLYoV6jo4Jk4J7_nKqqf7F2C6id3nHQltlEDYPQ39oLfK4oLqViqP1LTrmA66wA6jVbBRQOuQGWWx0Oxc72aDNdtS3WoQYNFIXZ-uyCrWncYV83Q2QjQ.FdwJlG7VbG8FpX75S9mLb0ynmr8fBli71VRD27DKD9U&dib_tag=se&keywords=On+the+Map%3A+A+Mind-expanding&qid=1705823976&s=books&sprefix=on+the+map+a+mind-expanding%2Cstripbooks-intl-ship%2C227&sr=1-1), New York, N.Y.: Gotham Books.) 제1장 선구자들이 그린 정말 이상한 지도. 25-50.

-   유나영 옮김. 2021. [지도의 역사: 지도로 그려진 최초의 발자취부터 인공지능까지](https://www.yes24.com/Product/Goods/104227876). 서울: 소소의책. (Swanston, Malcolm, and Alexander Swanston. 2019. [*How to Draw a Map*](https://www.amazon.com/How-to-Draw-a-Map/dp/0008275793/ref=sr_1_2?crid=215Q9RNBMV48J&dib=eyJ2IjoiMSJ9.DnuLacSDTLpZaYAPmIRSfz7vy-o7UERC3fTszoV0jhEEr8FXT1cDbT--r7xxnZmYB4jZ9jM5FXcvOnYk7dr27Vdwek5pU12DGGcykFuM2X_j6nAY4mw-MTRjhnWhUhlFmwwhI1_wYiFLxTOKjNPgDir8_GI4bKClkI3i1X1VB7zrj-noPbUOtGDMQ6feMKFvkoQ__K7T43W7D6vm6qU_rIVRdw96W-Gf0G09zFuMPk0.Lev427xXvPEXInx4RTCdzXCKrE_a4wiR7-ffvepb5xA&dib_tag=se&keywords=How+to+Draw+a+Map&qid=1705824019&s=books&sprefix=how+to+draw+a+map%2Cstripbooks-intl-ship%2C223&sr=1-2)*.* London: HarperCollinsPublishers.) 2. 시에네의 우물에 태양이 비칠때. 21-30.

[@berg2018]

## Video Materials

-   [Origin of the World Map](https://www.youtube.com/watch?v=AJBBVQrRwqo&t=2s)

    -   ShūBa̱ck
