---
title: "Hereford Mappa Mundi"
date-modified: last-modified
number-sections: false
bibliography: references.bib
---

## Synopsis

## References

-   Bevan, William Latham, and Henry Wright Phillott. 1873. *Mediæval Geography: An Essay in Illustration of the Hereford Mappa Mundi*. E. Stanford.

-   Brotton, Jerry. 2014. *Great Maps: The World’s Masterpieces Explored and Explained*. New York: Publishing. Hereford Mappa Mundi. 56-59.

-   De Wesselow, Thomas. 2013. “[Locating the Hereford *Mappamundi*](papers/de_wesselow_2013.pdf).” *Imago Mundi* 65 (2): 180–206. <https://doi.org/10.1080/03085694.2013.784555>.

-   Harvey, P. D. A. 1996. *Mappa Mundi: The Hereford World Map*. Toronto: University of Toronto Press.

-   Kline, Naomi Reed. 2003. *Maps of Medieval Thought: The Hereford Paradigm*. Woodbridge, Suffolk: Boydell Press.

-   Kupfer, Marcia Ann. 2016. *Art and Optics in the Hereford Map: An English Mappa Mundi, C. 1300*. New Haven: Yale University Press.

-   **MyOldMaps**, [#226 The Hereford Mappamundi](file:///C:/Users/User/Zotero/storage/N4WA7ZC6/226-the-hereford-mappamundi.html)

-   **김명남 옮김**. 2015. [지도 위의 인문학](https://www.yes24.com/Product/Goods/23544580): 지도 위에 그려진 인류 문명의 유쾌한 탐험, 파주: 다산북스. (Garfield, Simon. 2013. [*On the Map: A Mind-expanding Exploration of the Way the World Looks*](https://www.amazon.com/Map-Mind-Expanding-Exploration-Notable-Adults/dp/1592407803/ref=sr_1_1?crid=3BJW1GMAX4YZ5&dib=eyJ2IjoiMSJ9.lQGK5iKst9YJ8yMba6Ck0TRUHjQNFMzmbWXLYoV6jo4Jk4J7_nKqqf7F2C6id3nHQltlEDYPQ39oLfK4oLqViqP1LTrmA66wA6jVbBRQOuQGWWx0Oxc72aDNdtS3WoQYNFIXZ-uyCrWncYV83Q2QjQ.FdwJlG7VbG8FpX75S9mLb0ynmr8fBli71VRD27DKD9U&dib_tag=se&keywords=On+the+Map%3A+A+Mind-expanding&qid=1705823976&s=books&sprefix=on+the+map+a+mind-expanding%2Cstripbooks-intl-ship%2C227&sr=1-1), New York, N.Y.: Gotham Books.) 제2장 세계를 팔아넘긴 간 큰 남자들. 51-78.

-   **송태욱 옮김**, 2010, [세계 지도의 탄생](https://www.yes24.com/Product/Goods/3969693), 파주: 알마(応地利明, 2007, [「世界地圖」の誕生](https://www.amazon.com/Sekai-chizu-tanjo%C3%8C-kataru/dp/4532165830), 東京: 日本経済新聞出版社). 현존 최고의 헤리퍼드 세계지도. 90-171.

-   **이창신 옮김**. 2014. [욕망하는 지도: 12개의 지도로 읽는 세계사](https://www.yes24.com/Product/goods/12192777). 서울: 알에이치코리아. (Brotton, Jerry. 2012. [*A History of the World in 12 Maps*](https://www.amazon.com/History-World-12-Maps/dp/0143126024/ref=sr_1_1?crid=9UJLJ246IYSS&dib=eyJ2IjoiMSJ9.FY-MmIMOaa_OhpIKA0R7CHSpbeqP3wOtOFs1sSfDjxeQ8INh1JiJ-KQljiGWcA25hxz874-gObNXP3X5ux2xio52rPEJBPyZ7ZvLFDY0DDy8yLVU9scI67gu_NYK-0eK0EXvGAmeM6n4j8Vlbb5scmVYm88eBN25OVoCVQ_OnJwXaIQhrTFJBx88eP5I5jEQC0fdviI7qwn7JuLEicvdF9YVmfvRWbYyWu7okUNlW0A._mvJs7KogkSTGtuBdXenODFkqSV87AzIcwZwWisz9to&dib_tag=se&keywords=A+History+of+the+World+in+12+Maps&qid=1705823939&s=books&sprefix=a+history+of+the+world+in+12+maps%2Cstripbooks-intl-ship%2C217&sr=1-1)*.* New York: Viking.) 3 신앙: 헤리퍼드 마파문디, 1300년경. 137-178.

## Video Materials

-   [Why are Medieval Maps so Weird?](https://www.youtube.com/watch?v=TuXcA8l6zy8)

    -   ShūBa̱ck

-   [Medieval world map, Mappa Mundi, what does it show?](https://www.youtube.com/watch?v=n4uHbTtWbe8)

    -   Modern History TV

-   [The Hereford World Map: Mappa Mundi \| A limited edition from The Folio Society](https://www.youtube.com/watch?v=uO-IJUP_UBQ)

    -   The Folio Society
