---
title: "Ptolemaios"
date-modified: last-modified
number-sections: false
bibliography: references.bib
---

## Synopsis

## References

-   **Aujac, Germaine**. 2016. “[The “Revolution” of Ptolemy](papers/aujac_2016.pdf).” In *Brill's Companion to Ancient Geography*, edited by Serena Bianchetti, Michele Cataudella, and Hans-Joachim Gehrke, 311–34. Leiden, The Netherlands: BRILL. <https://doi.org/10.1163/9789004284715_019>.

-   **Berg, Thomas Reinertsen**. 2018. *Theater of the World: The Maps That Made History*. New York: Little, Brown; Company. Like Frogs about a Pond. 29-61.

-   Brotton, Jerry. 2014. *Great Maps: The World’s Masterpieces Explored and Explained*. New York: Publishing. Ptolemy's World Map, 24-27.

-   Bunbury, E. H. 1959. *A History of Ancient Geography Among the Greeks and Romans from the Earliest Ages till the Fall of the Roman Empire*. Vol. 1. New York: Dover Publications.

-   Bunbury, E. H. 1959. *A History of Ancient Geography Among the Greeks and Romans from the Earliest Ages till the Fall of the Roman Empire*. Vol. 2. New York: Dover Publications.

-   Dilke, Oswald Ashton Wentworth. 1985. *Greek and Roman Maps*. Ithaca, N.Y: Cornell University Press. V Ptolemy and Hist Predecessor Marinus. 72-86.

-   Jones, Alexander, ed. 2010. *Ptolemy in Perspective: Use and Criticism of His Work from Antiquity to the Nineteenth Century*. New York: Springer.

-   **Jones, Alexander**. 2012. “[Ptolemy’s Geography: Mapmaking and the Scientific Enterprise](papers/jones_2012.pdf).” In *Ancient Perspectives: Maps and Their Place in Mesopotamia, Egypt, Greece, and Rome*, edited by Richard J. A. Talbert, 109–128. Chicago: The University of Chicago Press.

-   **MyOldMaps**, [#119 Ptolemy](https://www.myoldmaps.com/maps-from-antiquity-6200-bc/116-pomponius/119-ptolemy/)

-   Ptolemy, Claudius. 1990. *Cosmography: Maps from Ptolemys "Geography"*. Wigston, Leicester: Magna Books.

-   **Ptolemy, Claudius**. (trans. by J. Lennart Berggren and Alexander Jones) 2000. *Ptolemy’s Geography: An Annotated Translation of the Theoretical Chapters*. Princeton, NJ: Princeton University Press.

-   Ptolemy, Claudius. (trans. by Edward Luther Stevenson and Joseph Fischer). 1991. *The Geography*. New York: Dover Publications.

-   Shalev, Zur, and Charles S. F. Burnett. 2011. *Ptolemy’s Geography in the Renaissance*. Warburg Institute.

-   Shcheglov, Dmitry A. 2004. “[Ptolemy’s System of Seven Climata and Eratosthenes’ Geography.](papers/shcheglov_2004.pdf)” *Geographia Antiqua* 13: 21–37.

-   **Shcheglov, Dmitry A**. 2016. “[The Error in Longitude in Ptolemy’s *Geography* Revisited](papers/shcheglov_2016.pdf).” *The Cartographic Journal* 53 (1): 3–14. <https://doi.org/10.1179/1743277414Y.0000000098>.

-   Shcheglov, Dmitry A. 2017. “[Eratosthenes’ Contribution to Ptolemy’s Map of the World](papers/shcheglov_2017.pdf).” *Imago Mundi* 69 (2): 159–75. <https://doi.org/10.1080/03085694.2017.1312112>.

-   Thomson, James Oliver. 1965. *History of Ancient Geography*. Biblo & Tannen Publishers.

-   Tupikova, Irina. 2014. “[Ptolemy’s Circumference of the Earth](papers/tupikova_2014.pdf).” TOPOI – Towards a Historical Epistemology of Space.

-   Tupikova, Irina, and Klaus Geus. 2013. “[The Circumference of the Earth and Ptolemy’s World Map](papers/tupikova_geus_2013.pdf).” *TOPOI Towards a Historical Epistemology of Space*.

-   김명남 옮김. 2015. [지도 위의 인문학](https://www.yes24.com/Product/Goods/23544580): 지도 위에 그려진 인류 문명의 유쾌한 탐험, 파주: 다산북스. (Garfield, Simon. 2013. [*On the Map: A Mind-expanding Exploration of the Way the World Looks*](https://www.amazon.com/Map-Mind-Expanding-Exploration-Notable-Adults/dp/1592407803/ref=sr_1_1?crid=3BJW1GMAX4YZ5&dib=eyJ2IjoiMSJ9.lQGK5iKst9YJ8yMba6Ck0TRUHjQNFMzmbWXLYoV6jo4Jk4J7_nKqqf7F2C6id3nHQltlEDYPQ39oLfK4oLqViqP1LTrmA66wA6jVbBRQOuQGWWx0Oxc72aDNdtS3WoQYNFIXZ-uyCrWncYV83Q2QjQ.FdwJlG7VbG8FpX75S9mLb0ynmr8fBli71VRD27DKD9U&dib_tag=se&keywords=On+the+Map%3A+A+Mind-expanding&qid=1705823976&s=books&sprefix=on+the+map+a+mind-expanding%2Cstripbooks-intl-ship%2C227&sr=1-1), New York, N.Y.: Gotham Books.) 제1장 선구자들이 그린 정말 이상한 지도. 25-50.

-   **송태욱 옮김**, 2010, [세계 지도의 탄생](https://www.yes24.com/Product/Goods/3969693), 파주: 알마(応地利明, 2007, [「世界地圖」の誕生](https://www.amazon.com/Sekai-chizu-tanjo%C3%8C-kataru/dp/4532165830), 東京: 日本経済新聞出版社). 고대 그리스와 로마 시대를 대표하는 프톨레마이오스 세계지도. 209-223.

-   유나영 옮김. 2021. [지도의 역사: 지도로 그려진 최초의 발자취부터 인공지능까지](https://www.yes24.com/Product/Goods/104227876). 서울: 소소의책. (Swanston, Malcolm, and Alexander Swanston. 2019. [*How to Draw a Map*](https://www.amazon.com/How-to-Draw-a-Map/dp/0008275793/ref=sr_1_2?crid=215Q9RNBMV48J&dib=eyJ2IjoiMSJ9.DnuLacSDTLpZaYAPmIRSfz7vy-o7UERC3fTszoV0jhEEr8FXT1cDbT--r7xxnZmYB4jZ9jM5FXcvOnYk7dr27Vdwek5pU12DGGcykFuM2X_j6nAY4mw-MTRjhnWhUhlFmwwhI1_wYiFLxTOKjNPgDir8_GI4bKClkI3i1X1VB7zrj-noPbUOtGDMQ6feMKFvkoQ__K7T43W7D6vm6qU_rIVRdw96W-Gf0G09zFuMPk0.Lev427xXvPEXInx4RTCdzXCKrE_a4wiR7-ffvepb5xA&dib_tag=se&keywords=How+to+Draw+a+Map&qid=1705824019&s=books&sprefix=how+to+draw+a+map%2Cstripbooks-intl-ship%2C223&sr=1-2)*.* London: HarperCollinsPublishers.) 3 로마의 유산. 31-42.

-   **이창신 옮김**. 2014. [욕망하는 지도: 12개의 지도로 읽는 세계사](https://www.yes24.com/Product/goods/12192777). 서울: 알에이치코리아. (Brotton, Jerry. 2012. [*A History of the World in 12 Maps*](https://www.amazon.com/History-World-12-Maps/dp/0143126024/ref=sr_1_1?crid=9UJLJ246IYSS&dib=eyJ2IjoiMSJ9.FY-MmIMOaa_OhpIKA0R7CHSpbeqP3wOtOFs1sSfDjxeQ8INh1JiJ-KQljiGWcA25hxz874-gObNXP3X5ux2xio52rPEJBPyZ7ZvLFDY0DDy8yLVU9scI67gu_NYK-0eK0EXvGAmeM6n4j8Vlbb5scmVYm88eBN25OVoCVQ_OnJwXaIQhrTFJBx88eP5I5jEQC0fdviI7qwn7JuLEicvdF9YVmfvRWbYyWu7okUNlW0A._mvJs7KogkSTGtuBdXenODFkqSV87AzIcwZwWisz9to&dib_tag=se&keywords=A+History+of+the+World+in+12+Maps&qid=1705823939&s=books&sprefix=a+history+of+the+world+in+12+maps%2Cstripbooks-intl-ship%2C217&sr=1-1)*.* New York: Viking.) 1 과학: 프톨레마이오스의 지리학, 서기 150년경. 45-93.

## Video Materials

-   [Schemes of Annotation in Ptolemy's Geography](https://www.youtube.com/watch?v=CtmeBNWrLrU)

    -   Library of Congress, U.S.

-   [The Ptolemy Atlas](https://www.youtube.com/watch?v=qjdmbIs9Ay0)

    -   Ziereis Facsimiles
